server:
  port: 8081

spring:
  application:
    name: school-service

  datasource:
    url: jdbc:mysql://localhost:3306/school_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://default.auth.example.com:9000


logging:
  level:
    org.springframework.security: DEBUG
