spring:
  application:
    name: resource-server

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:9000/realms/{realm}

auth-server:
  base-url: https://localhost:9000
